//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command.txt
// Note: requires additional types generated from: scene.txt
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ReleaseSkill")]
  public partial class CMD_ReleaseSkill : global::ProtoBuf.IExtensible
  {
    public CMD_ReleaseSkill() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private PBMessage.Position3D _mouseposition;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mouseposition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Position3D mouseposition
    {
      get { return _mouseposition; }
      set { _mouseposition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_MoveToPoint")]
  public partial class CMD_MoveToPoint : global::ProtoBuf.IExtensible
  {
    public CMD_MoveToPoint() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private PBMessage.Position3D _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Position3D position
    {
      get { return _position; }
      set { _position = value; }
    }
    private PBMessage.Position3D _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Position3D direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private PBMessage.Position3D _destination;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"destination", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.Position3D destination
    {
      get { return _destination; }
      set { _destination = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Disconnect")]
  public partial class Disconnect : global::ProtoBuf.IExtensible
  {
    public Disconnect() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeepAliveMsg")]
  public partial class KeepAliveMsg : global::ProtoBuf.IExtensible
  {
    public KeepAliveMsg() {}
    
    private PBMessage.CurScene _curScene;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"curScene", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.CurScene curScene
    {
      get { return _curScene; }
      set { _curScene = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReturn")]
  public partial class LoginReturn : global::ProtoBuf.IExtensible
  {
    public LoginReturn() {}
    
    private string _sessionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private PBMessage.LoginReturnType _returnType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"returnType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.LoginReturnType returnType
    {
      get { return _returnType; }
      set { _returnType = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMessage.PlayerInfo> _playerInfo = new global::System.Collections.Generic.List<PBMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.PlayerInfo> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterRequest")]
  public partial class RegisterRequest : global::ProtoBuf.IExtensible
  {
    public RegisterRequest() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterReturn")]
  public partial class RegisterReturn : global::ProtoBuf.IExtensible
  {
    public RegisterReturn() {}
    
    private PBMessage.RegisterReturnType _returnType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"returnType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.RegisterReturnType returnType
    {
      get { return _returnType; }
      set { _returnType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoleRequest")]
  public partial class CreateRoleRequest : global::ProtoBuf.IExtensible
  {
    public CreateRoleRequest() {}
    
    private string _sessionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private PBMessage.PlayerInfo _playerInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoleReturn")]
  public partial class CreateRoleReturn : global::ProtoBuf.IExtensible
  {
    public CreateRoleReturn() {}
    
    private PBMessage.CreateRoleReturnType _returnType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"returnType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.CreateRoleReturnType returnType
    {
      get { return _returnType; }
      set { _returnType = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMessage.PlayerInfo> _playerInfo = new global::System.Collections.Generic.List<PBMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.PlayerInfo> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectRoleRequest")]
  public partial class SelectRoleRequest : global::ProtoBuf.IExtensible
  {
    public SelectRoleRequest() {}
    
    private string _sessionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private int _roleType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleType
    {
      get { return _roleType; }
      set { _roleType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectRoleReturn")]
  public partial class SelectRoleReturn : global::ProtoBuf.IExtensible
  {
    public SelectRoleReturn() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallRequest")]
  public partial class HallRequest : global::ProtoBuf.IExtensible
  {
    public HallRequest() {}
    
    private string _sessionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private PBMessage.HallMsgType _MsgType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MsgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.HallMsgType MsgType
    {
      get { return _MsgType; }
      set { _MsgType = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private PBMessage.InviteInfo _inviteInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"inviteInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.InviteInfo inviteInfo
    {
      get { return _inviteInfo; }
      set { _inviteInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallReturn")]
  public partial class HallReturn : global::ProtoBuf.IExtensible
  {
    public HallReturn() {}
    
    private PBMessage.HallInfo _hallInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hallInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.HallInfo hallInfo
    {
      get { return _hallInfo; }
      set { _hallInfo = value; }
    }
    private PBMessage.HallMsgType _MsgType = PBMessage.HallMsgType.HST_AutoMatch;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MsgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.HallMsgType.HST_AutoMatch)]
    public PBMessage.HallMsgType MsgType
    {
      get { return _MsgType; }
      set { _MsgType = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMessage.PlayerInfo> _friendList = new global::System.Collections.Generic.List<PBMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.PlayerInfo> friendList
    {
      get { return _friendList; }
    }
  
    private PBMessage.InviteInfo _inviteInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"inviteInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.InviteInfo inviteInfo
    {
      get { return _inviteInfo; }
      set { _inviteInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMainRequest")]
  public partial class GameMainRequest : global::ProtoBuf.IExtensible
  {
    public GameMainRequest() {}
    
    private string _sessionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private PBMessage.GameMainMsgType _msgType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.GameMainMsgType msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private PBMessage.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMainReturn")]
  public partial class GameMainReturn : global::ProtoBuf.IExtensible
  {
    public GameMainReturn() {}
    
    private PBMessage.GameMainMsgType _msgType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.GameMainMsgType msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMessage.PlayerInfo> _friendList = new global::System.Collections.Generic.List<PBMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.PlayerInfo> friendList
    {
      get { return _friendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Packet")]
  public partial class Packet : global::ProtoBuf.IExtensible
  {
    public Packet() {}
    
    private PBMessage.CurScene _curScene;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"curScene", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.CurScene curScene
    {
      get { return _curScene; }
      set { _curScene = value; }
    }
    private PBMessage.MessageType _msgType = PBMessage.MessageType.IdInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.MessageType.IdInfo)]
    public PBMessage.MessageType msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private PBMessage.LoginRequest _loginRequest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.LoginRequest loginRequest
    {
      get { return _loginRequest; }
      set { _loginRequest = value; }
    }
    private PBMessage.LoginReturn _loginReturn = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.LoginReturn loginReturn
    {
      get { return _loginReturn; }
      set { _loginReturn = value; }
    }
    private PBMessage.RegisterRequest _registerRequest = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"registerRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.RegisterRequest registerRequest
    {
      get { return _registerRequest; }
      set { _registerRequest = value; }
    }
    private PBMessage.RegisterReturn _registerReturn = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"registerReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.RegisterReturn registerReturn
    {
      get { return _registerReturn; }
      set { _registerReturn = value; }
    }
    private PBMessage.CreateRoleRequest _createRoleRequest = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"createRoleRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.CreateRoleRequest createRoleRequest
    {
      get { return _createRoleRequest; }
      set { _createRoleRequest = value; }
    }
    private PBMessage.CreateRoleReturn _createRoleReturn = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"createRoleReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.CreateRoleReturn createRoleReturn
    {
      get { return _createRoleReturn; }
      set { _createRoleReturn = value; }
    }
    private PBMessage.SelectRoleRequest _selectRoleRequest = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"selectRoleRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.SelectRoleRequest selectRoleRequest
    {
      get { return _selectRoleRequest; }
      set { _selectRoleRequest = value; }
    }
    private PBMessage.SelectRoleReturn _selectRoleReturn = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"selectRoleReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.SelectRoleReturn selectRoleReturn
    {
      get { return _selectRoleReturn; }
      set { _selectRoleReturn = value; }
    }
    private PBMessage.HallRequest _hallRequest = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hallRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.HallRequest hallRequest
    {
      get { return _hallRequest; }
      set { _hallRequest = value; }
    }
    private PBMessage.HallReturn _hallReturn = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"hallReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.HallReturn hallReturn
    {
      get { return _hallReturn; }
      set { _hallReturn = value; }
    }
    private PBMessage.GameMainRequest _gameMainRequest = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gameMainRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.GameMainRequest gameMainRequest
    {
      get { return _gameMainRequest; }
      set { _gameMainRequest = value; }
    }
    private PBMessage.GameMainReturn _gameMainReturn = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"gameMainReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.GameMainReturn gameMainReturn
    {
      get { return _gameMainReturn; }
      set { _gameMainReturn = value; }
    }
    private PBMessage.KeepAliveMsg _keepAlive = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"keepAlive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.KeepAliveMsg keepAlive
    {
      get { return _keepAlive; }
      set { _keepAlive = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnPacket")]
  public partial class UnPacket : global::ProtoBuf.IExtensible
  {
    public UnPacket() {}
    
    private PBMessage.CurScene _curScene;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"curScene", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.CurScene curScene
    {
      get { return _curScene; }
      set { _curScene = value; }
    }
    private PBMessage.MessageType _msgType = PBMessage.MessageType.IdInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.MessageType.IdInfo)]
    public PBMessage.MessageType msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private PBMessage.LoginRequest _loginRequest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.LoginRequest loginRequest
    {
      get { return _loginRequest; }
      set { _loginRequest = value; }
    }
    private PBMessage.LoginReturn _loginReturn = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.LoginReturn loginReturn
    {
      get { return _loginReturn; }
      set { _loginReturn = value; }
    }
    private PBMessage.RegisterRequest _registerRequest = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"registerRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.RegisterRequest registerRequest
    {
      get { return _registerRequest; }
      set { _registerRequest = value; }
    }
    private PBMessage.RegisterReturn _registerReturn = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"registerReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.RegisterReturn registerReturn
    {
      get { return _registerReturn; }
      set { _registerReturn = value; }
    }
    private PBMessage.CreateRoleRequest _createRoleRequest = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"createRoleRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.CreateRoleRequest createRoleRequest
    {
      get { return _createRoleRequest; }
      set { _createRoleRequest = value; }
    }
    private PBMessage.CreateRoleReturn _createRoleReturn = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"createRoleReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.CreateRoleReturn createRoleReturn
    {
      get { return _createRoleReturn; }
      set { _createRoleReturn = value; }
    }
    private PBMessage.SelectRoleRequest _selectRoleRequest = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"selectRoleRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.SelectRoleRequest selectRoleRequest
    {
      get { return _selectRoleRequest; }
      set { _selectRoleRequest = value; }
    }
    private PBMessage.SelectRoleReturn _selectRoleReturn = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"selectRoleReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.SelectRoleReturn selectRoleReturn
    {
      get { return _selectRoleReturn; }
      set { _selectRoleReturn = value; }
    }
    private PBMessage.HallRequest _hallRequest = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hallRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.HallRequest hallRequest
    {
      get { return _hallRequest; }
      set { _hallRequest = value; }
    }
    private PBMessage.HallReturn _hallReturn = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"hallReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.HallReturn hallReturn
    {
      get { return _hallReturn; }
      set { _hallReturn = value; }
    }
    private PBMessage.GameMainRequest _gameMainRequest = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gameMainRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.GameMainRequest gameMainRequest
    {
      get { return _gameMainRequest; }
      set { _gameMainRequest = value; }
    }
    private PBMessage.GameMainReturn _gameMainReturn = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"gameMainReturn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.GameMainReturn gameMainReturn
    {
      get { return _gameMainReturn; }
      set { _gameMainReturn = value; }
    }
    private PBMessage.KeepAliveMsg _keepAlive = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"keepAlive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.KeepAliveMsg keepAlive
    {
      get { return _keepAlive; }
      set { _keepAlive = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CommandID")]
    public enum CommandID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReleaseSkill", Value=1)]
      ReleaseSkill = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveToPoint", Value=2)]
      MoveToPoint = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CurScene")]
    public enum CurScene
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_None", Value=0)]
      CS_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_Login", Value=1)]
      CS_Login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_Register", Value=2)]
      CS_Register = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_CreateRole", Value=3)]
      CS_CreateRole = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_SelectRole", Value=4)]
      CS_SelectRole = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_WaitRoom", Value=5)]
      CS_WaitRoom = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_MainScene", Value=6)]
      CS_MainScene = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_KeepAlive", Value=7)]
      CS_KeepAlive = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_BreakLineRecon", Value=8)]
      CS_BreakLineRecon = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IdInfo", Value=0)]
      IdInfo = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateInfo", Value=1)]
      CreateInfo = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TextInfo", Value=2)]
      TextInfo = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveInfo", Value=3)]
      MoveInfo = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DestroyInfo", Value=4)]
      DestroyInfo = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsynInfo", Value=5)]
      AsynInfo = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginReturnType")]
    public enum LoginReturnType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Fail", Value=0)]
      Fail = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ToCreateRole", Value=1)]
      ToCreateRole = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ToSelectRole", Value=2)]
      ToSelectRole = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RegisterReturnType")]
    public enum RegisterReturnType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_Fail", Value=0)]
      RT_Fail = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_Success", Value=1)]
      RT_Success = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CreateRoleReturnType")]
    public enum CreateRoleReturnType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRT_Fail", Value=0)]
      CRT_Fail = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRT_Success", Value=1)]
      CRT_Success = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HallMsgType")]
    public enum HallMsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_AutoMatch", Value=0)]
      HST_AutoMatch = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_CreateRoom", Value=1)]
      HST_CreateRoom = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_GetRoomList", Value=2)]
      HST_GetRoomList = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_JoinRoom", Value=3)]
      HST_JoinRoom = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_GameStart", Value=4)]
      HST_GameStart = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_WaitTimeout", Value=5)]
      HST_WaitTimeout = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_LeaveRoom", Value=6)]
      HST_LeaveRoom = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_CreateRoomFail", Value=7)]
      HST_CreateRoomFail = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_OnlineFriend", Value=8)]
      HST_OnlineFriend = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_RequestTeam", Value=9)]
      HST_RequestTeam = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_JoinTeam", Value=10)]
      HST_JoinTeam = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_GameWaite", Value=11)]
      HST_GameWaite = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HST_KeepAlive", Value=12)]
      HST_KeepAlive = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameMainMsgType")]
    public enum GameMainMsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMT_KeepAlive", Value=0)]
      GMT_KeepAlive = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMT_RsyncAttr", Value=1)]
      GMT_RsyncAttr = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMT_RsyncStatus", Value=2)]
      GMT_RsyncStatus = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMT_GameOver", Value=3)]
      GMT_GameOver = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMT_BreakLine", Value=4)]
      GMT_BreakLine = 4
    }
  
}
// Generated from: scene.txt
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position2D")]
  public partial class Position2D : global::ProtoBuf.IExtensible
  {
    public Position2D() {}
    
    private string _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string x
    {
      get { return _x; }
      set { _x = value; }
    }
    private string _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position3D")]
  public partial class Position3D : global::ProtoBuf.IExtensible
  {
    public Position3D() {}
    
    private string _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string x
    {
      get { return _x; }
      set { _x = value; }
    }
    private string _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string y
    {
      get { return _y; }
      set { _y = value; }
    }
    private string _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _socket = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"socket", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int socket
    {
      get { return _socket; }
      set { _socket = value; }
    }
    private bool _isRoomCtl = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isRoomCtl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isRoomCtl
    {
      get { return _isRoomCtl; }
      set { _isRoomCtl = value; }
    }
    private int _roleId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _roleType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleType
    {
      get { return _roleType; }
      set { _roleType = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _mp = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private float _attack = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private float _moveSpeed = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private PBMessage.TeamType _team = PBMessage.TeamType.Team_A;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.TeamType.Team_A)]
    public PBMessage.TeamType team
    {
      get { return _team; }
      set { _team = value; }
    }
    private PBMessage.RoomType _roomState = PBMessage.RoomType.RT_Idle;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.RoomType.RT_Idle)]
    public PBMessage.RoomType roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _teamId = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private bool _gameWaite = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"gameWaite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool gameWaite
    {
      get { return _gameWaite; }
      set { _gameWaite = value; }
    }
    private PBMessage.Position3D _Pos = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.Position3D Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private PBMessage.Position3D _Rot = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Rot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.Position3D Rot
    {
      get { return _Rot; }
      set { _Rot = value; }
    }
    private PBMessage.Position3D _Scale = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"Scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBMessage.Position3D Scale
    {
      get { return _Scale; }
      set { _Scale = value; }
    }
    private PBMessage.PlayerStatus _playerStatus = PBMessage.PlayerStatus.PS_None;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"playerStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.PlayerStatus.PS_None)]
    public PBMessage.PlayerStatus playerStatus
    {
      get { return _playerStatus; }
      set { _playerStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallInfo")]
  public partial class HallInfo : global::ProtoBuf.IExtensible
  {
    public HallInfo() {}
    
    private readonly global::System.Collections.Generic.List<PBMessage.RoomInfo> _roomInfo = new global::System.Collections.Generic.List<PBMessage.RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.RoomInfo> roomInfo
    {
      get { return _roomInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private int _personCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"personCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int personCount
    {
      get { return _personCount; }
      set { _personCount = value; }
    }
    private int _freePersonCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"freePersonCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int freePersonCount
    {
      get { return _freePersonCount; }
      set { _freePersonCount = value; }
    }
    private readonly global::System.Collections.Generic.List<PBMessage.PlayerInfo> _playerInfo = new global::System.Collections.Generic.List<PBMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBMessage.PlayerInfo> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteInfo")]
  public partial class InviteInfo : global::ProtoBuf.IExtensible
  {
    public InviteInfo() {}
    
    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private int _reqUserId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reqUserId
    {
      get { return _reqUserId; }
      set { _reqUserId = value; }
    }
    private string _reqUserName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reqUserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqUserName
    {
      get { return _reqUserName; }
      set { _reqUserName = value; }
    }
    private int _revUserId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"revUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int revUserId
    {
      get { return _revUserId; }
      set { _revUserId = value; }
    }
    private PBMessage.TeamType _team = PBMessage.TeamType.Team_A;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(PBMessage.TeamType.Team_A)]
    public PBMessage.TeamType team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _teamId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamType")]
    public enum TeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Team_A", Value=1)]
      Team_A = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Team_B", Value=2)]
      Team_B = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomType")]
    public enum RoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_Idle", Value=1)]
      RT_Idle = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_JoinRoom", Value=2)]
      RT_JoinRoom = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_Wait", Value=3)]
      RT_Wait = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_OK", Value=4)]
      RT_OK = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerStatus")]
    public enum PlayerStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_None", Value=0)]
      PS_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_Idle", Value=1)]
      PS_Idle = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_Run", Value=2)]
      PS_Run = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_Q", Value=3)]
      PS_Q = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_W", Value=4)]
      PS_W = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_E", Value=5)]
      PS_E = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_R", Value=6)]
      PS_R = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_Death", Value=7)]
      PS_Death = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_CDing", Value=8)]
      PS_CDing = 8
    }
  
}